package com.orangehrm.tests;

import com.orangehrm.base.BaseTest;
import com.orangehrm.models.Employee;
import com.orangehrm.pages.EmployeePage;
import com.orangehrm.pages.PIMPage;
import com.orangehrm.utils.RetryAnalyzer;
import com.orangehrm.utils.TestDataGenerator;
import org.testng.Assert;
import org.testng.annotations.Test;

public class EmployeeCreationTest extends BaseTest {

    @Test(groups = {"employee", "smoke", "regression"},
          description = "Admin can create a new employee with basic details",
          retryAnalyzer = RetryAnalyzer.class)
    public void testCreateEmployeeWithBasicDetails() {
        Employee newEmployee = TestDataGenerator.generateEmployee();

        PIMPage pimPage = loginAsAdmin().navigateToPIM();
        EmployeePage employeePage = pimPage.addEmployee(newEmployee);

        registerEmployeeForCleanup(employeePage.getEmployeeId());

        String currentUrl = driver.getCurrentUrl();
        Assert.assertTrue(currentUrl.contains("/pim/viewPersonalDetails"),
                "Should navigate to employee profile after creation. URL: " + currentUrl);

        String headerName = employeePage.getEmployeeNameFromHeader();
        Assert.assertTrue(headerName.contains(newEmployee.getFirstName()));
        Assert.assertTrue(headerName.contains(newEmployee.getLastName()));
    }

    @Test(groups = {"employee", "regression"},
          description = "Created employee appears in employee list",
          retryAnalyzer = RetryAnalyzer.class)
    public void testCreatedEmployeeAppearsInList() {
        Employee newEmployee = TestDataGenerator.generateEmployee();

        PIMPage pimPage = loginAsAdmin().navigateToPIM();
        EmployeePage employeePage = pimPage.addEmployee(newEmployee);

        String employeeId = employeePage.getEmployeeId();
        registerEmployeeForCleanup(employeeId);

        driver.navigate().to(config.getBaseUrl() + "/web/index.php/pim/viewEmployeeList");
        pimPage.searchByEmployeeId(employeeId);

        Assert.assertTrue(pimPage.getRowCount() > 0,
                "Employee should appear in the list after creation");
    }

    @Test(groups = {"employee", "regression"},
          description = "Employee ID is auto-generated if not specified")
    public void testEmployeeIdAutoGenerated() {
        Employee newEmployee = Employee.builder()
                .firstName(TestDataGenerator.randomAlpha(7))
                .lastName(TestDataGenerator.randomAlpha(7))
                .build();

        PIMPage pimPage = loginAsAdmin().navigateToPIM();
        EmployeePage employeePage = pimPage.addEmployee(newEmployee);

        String employeeId = employeePage.getEmployeeId();
        registerEmployeeForCleanup(employeeId);

        Assert.assertNotNull(employeeId);
        Assert.assertFalse(employeeId.isEmpty());
    }

    @Test(groups = {"employee", "regression"},
          description = "Employee profile URL contains numeric employee number after creation")
    public void testEmployeeProfileUrlFormat() {
        Employee newEmployee = TestDataGenerator.generateEmployee();

        PIMPage pimPage = loginAsAdmin().navigateToPIM();
        EmployeePage employeePage = pimPage.addEmployee(newEmployee);

        registerEmployeeForCleanup(employeePage.getEmployeeId());

        String empNumber = employeePage.extractEmployeeIdFromUrl();
        Assert.assertFalse(empNumber.isEmpty());

        try {
            Integer.parseInt(empNumber);
        } catch (NumberFormatException e) {
            Assert.fail("Employee number should be numeric, got: " + empNumber);
        }
    }

    @Test(groups = {"employee", "regression"},
          description = "Multiple employees can be created independently")
    public void testCreateMultipleEmployees() {
        Employee emp1 = TestDataGenerator.generateEmployee();
        Employee emp2 = TestDataGenerator.generateEmployee();

        PIMPage pimPage = loginAsAdmin().navigateToPIM();

        EmployeePage employeePage1 = pimPage.addEmployee(emp1);
        registerEmployeeForCleanup(employeePage1.getEmployeeId());

        driver.navigate().to(config.getBaseUrl() + "/web/index.php/pim/viewEmployeeList");

        EmployeePage employeePage2 = pimPage.addEmployee(emp2);
        registerEmployeeForCleanup(employeePage2.getEmployeeId());

        Assert.assertTrue(driver.getCurrentUrl().contains("/pim/viewPersonalDetails"));
    }
}
