package com.orangehrm.tests;

import com.orangehrm.base.BaseTest;
import com.orangehrm.models.Employee;
import com.orangehrm.pages.EmployeePage;
import com.orangehrm.pages.PIMPage;
import com.orangehrm.utils.RetryAnalyzer;
import com.orangehrm.utils.TestDataGenerator;
import org.testng.Assert;
import org.testng.annotations.Test;

public class EmployeeCreationTest extends BaseTest {

    @Test(
        groups = {"employee", "smoke", "regression"},
        description = "Admin can create a new employee with basic details",
        retryAnalyzer = RetryAnalyzer.class
    )
    public void testCreateEmployeeWithBasicDetails() {
        Employee newEmployee = TestDataGenerator.generateEmployee();

        PIMPage pimPage = loginAsAdmin().navigateToPIM();
        EmployeePage employeePage = pimPage.addEmployee(newEmployee);

        String currentUrl = driver.getCurrentUrl();
        Assert.assertTrue(currentUrl.contains("/pim/viewPersonalDetails"),
                "Should navigate to employee profile after creation. URL: " + currentUrl);

        // Verify via the employee name header (plain text element — reliable across Vue re-renders)
        String headerName = employeePage.getEmployeeNameFromHeader();
        Assert.assertTrue(headerName.contains(newEmployee.getFirstName()),
                "Header should contain first name. Header was: " + headerName);
        Assert.assertTrue(headerName.contains(newEmployee.getLastName()),
                "Header should contain last name. Header was: " + headerName);

        log.info("Successfully created employee: {}", headerName);
    }

    @Test(
        groups = {"employee", "regression"},
        description = "Created employee appears in employee list",
        retryAnalyzer = RetryAnalyzer.class
    )
    public void testCreatedEmployeeAppearsInList() {
        Employee newEmployee = TestDataGenerator.generateEmployee();

        PIMPage pimPage = loginAsAdmin().navigateToPIM();
        pimPage.addEmployee(newEmployee);

        driver.navigate().to(config.getBaseUrl() + "/web/index.php/pim/viewEmployeeList");

        pimPage.searchByEmployeeId(newEmployee.getEmployeeId() != null ? newEmployee.getEmployeeId() : "");
        pimPage.clickSearch();

        int count = pimPage.getRowCount();
        Assert.assertTrue(count > 0,
                "Employee should appear in the list after creation");
    }

    @Test(
        groups = {"employee", "regression"},
        description = "Employee ID is auto-generated if not specified"
    )
    public void testEmployeeIdAutoGenerated() {
        Employee newEmployee = Employee.builder()
                .firstName(TestDataGenerator.randomAlpha(7))
                .lastName(TestDataGenerator.randomAlpha(7))
                .build();

        PIMPage pimPage = loginAsAdmin().navigateToPIM();
        EmployeePage employeePage = pimPage.addEmployee(newEmployee);

        String employeeId = employeePage.getEmployeeId();
        Assert.assertNotNull(employeeId, "Employee ID should be auto-generated");
        Assert.assertFalse(employeeId.isEmpty(), "Employee ID should not be empty");
        log.info("Auto-generated Employee ID: {}", employeeId);
    }

    @Test(
        groups = {"employee", "regression"},
        description = "Employee profile URL contains numeric employee number after creation"
    )
    public void testEmployeeProfileUrlFormat() {
        Employee newEmployee = TestDataGenerator.generateEmployee();

        PIMPage pimPage = loginAsAdmin().navigateToPIM();
        EmployeePage employeePage = pimPage.addEmployee(newEmployee);

        String empNumber = employeePage.extractEmployeeIdFromUrl();
        Assert.assertFalse(empNumber.isEmpty(), "Employee number should be in URL");

        try {
            Integer.parseInt(empNumber);
            log.info("Employee number extracted from URL: {}", empNumber);
        } catch (NumberFormatException e) {
            Assert.fail("Employee number in URL should be numeric, got: " + empNumber);
        }
    }

    @Test(
        groups = {"employee", "regression"},
        description = "Multiple employees can be created independently"
    )
    public void testCreateMultipleEmployees() {
        Employee emp1 = TestDataGenerator.generateEmployee();
        Employee emp2 = TestDataGenerator.generateEmployee();

        PIMPage pimPage = loginAsAdmin().navigateToPIM();

        pimPage.addEmployee(emp1);
        log.info("Created employee 1: {}", emp1.getFullName());

        driver.navigate().to(config.getBaseUrl() + "/web/index.php/pim/viewEmployeeList");

        pimPage.addEmployee(emp2);
        log.info("Created employee 2: {}", emp2.getFullName());

        Assert.assertTrue(driver.getCurrentUrl().contains("/pim/viewPersonalDetails"),
                "Should be on employee profile page");
    }
}
